version: '3'

services:
  sa.corpoperationplatform.api:
    image: sa.corpoperationplatform.api
    build:
      context: ./src/SA.CorpOperationPlatform.Api
      dockerfile: Dockerfile
    depends_on:
      - pg-db
  pg-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=cop
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test